[project]
authors = [{name = "Victor Hogeweij", email = "hogeweyv@gmail.com"}]
dependencies = [
    "fastapi>=0.100.0",
    "python-multipart>=0.0.6",
]
name = "upload_interface"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
upload_interface = { path = ".", editable = true }

[tool.pixi.tasks]
backend = { cmd = "uvicorn backend.main:app --port 8000 --reload", cwd = "src" }
frontend = { cmd = "npm run dev", cwd = "src/frontend" }
